package hypr.a255bits.com.hypr.Util

enum class AnalyticsEvent{
    GENERATOR_DOWNLOAD, EXISTING_PHOTO, TAKE_PICTURE,
    SHARE_IMAGE, SAVE_IMAGE, CHOOSE_SIDE_NAV_OPTION,
    CHOOSE_HOME_NAV_OPTION, CLICK_BUY_BUTTON, BOUGHT_ITEM
}
